### ISSUE TITLE
"macos-10.15" runner no longer exists since 2022

### ISSUE THREAD

**Issue by jrobichaud** [GabLeRoux/cv.gableroux.com#23]
https://github.com/GabLeRoux/cv.gableroux.com/blob/main/.github/workflows/main.yml#L11

https://github.blog/changelog/2022-07-20-github-actions-the-macos-10-15-actions-runner-image-is-being-deprecated-and-will-be-removed-by-8-30-22/

**Comment by GabLeRoux** [comment]
closed by 37aeb02 ;)
